language: cpp

sudo: required
dist: xenial

script: .travis/script.sh

matrix:
  include:
    - env: BUILD_TARGET="pretty-check"
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-format-6.0
    - env: BUILD_TARGET="nrf-check"
      os: linux
    - env: BUILD_TARGET="linux-check"
      os: linux
