#!/bin/bash
#
#  Copyright (c) 2018, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#    Description:
#      This file runs various tests.
#

set -e
set -o pipefail

readonly BUILD_JOBS="$(getconf _NPROCESSORS_ONLN)"
readonly BUILD_DIR=build
readonly PLATFORM_NAME="${PLATFORM:-nrf52}"

build() {
    [[ -d "${BUILD_DIR}" ]] || mkdir "${BUILD_DIR}"
    (cd "${BUILD_DIR}" && cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-none-eabi.cmake -DPLATFORM_NAME="${PLATFORM_NAME}" && make -j${BUILD_JOBS})
}

rebuild() {
    [[ ! -d "${BUILD_DIR}" ]] || rm -rf "${BUILD_DIR}"

    build
}

print_usage() {
    cat <<EOF
USAGE: $0 COMMAND

COMMAND:
    build       Build project to run tests.
    rebuild     Rebuild project to run tests.
    help        Print this help.

EXAMPLES:
    $0 rebuild
EOF
}

main()
{
    case "$1" in
        build)
            build
            ;;
        rebuild)
            rebuild
            ;;
        *)
            print_usage
            ;;
    esac
}

main "$@"
